name: qr_stringify
description: A package to convert a QR code to a pretty nicely formated string.
version: 0.0.1-dev.1
homepage: https://github.com/yardexx/qr_stringify
repository: https://github.com/yardexx/qr_stringify

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  test: ^1.22.0
  very_good_analysis: ">=3.1.0 <5.0.0"

dependencies:
  qr: ^3.0.1
